# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionName: "TestWeb"               #要构建的解决方案名称
  csprojDir: "TestWeb/TestWeb.csproj"   #.csproj文件全路径
  containerName: "testweb"              #容器名
  port: 5000                            #制定run的端口

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.106' # replace this value with the version that you need for your project
- script: dotnet restore
  displayName: 'dotnet restore  $(buildConfiguration)'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
